apiVersion: v1
kind: Agent
metadata:
  name: vision-assistant
spec:
  entrypoint: main.py
  runtime:
    python:
      version: "3.11"
  resources:
    cpu: 1000m
    memory: 1Gi
  env:
    - name: GOOGLE_API_KEY
      valueForm:
        secretKeyRef:
          name: google-credentials
          key: api-key