name: Deploy Agent to LiveKit Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'agent/**'
      - '!agent/livekit.toml'
      - '!agent/README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-agent
      cancel-in-progress: true
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to LiveKit Cloud
        uses: livekit/deploy-action@main
        env:
          LIVEKIT_URL: ${{ secrets.LIVEKIT_URL }}
          LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
          SECRET_LIST: ${{ secrets.SECRET_LIST }}
        with:
          OPERATION: deploy
          WORKING_DIRECTORY: agent
